create table public.professional_profiles (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  full_name text null,
  headline text null,
  location text null,
  email text null,
  phone text null,
  website text null,
  linkedin text null,
  professional_summary text null,
  years_experience integer null,
  skills text[] null default '{}'::text[],
  current_position jsonb null default '{}'::jsonb,
  work_experience jsonb null default '[]'::jsonb,
  education jsonb null default '[]'::jsonb,
  certifications jsonb null default '[]'::jsonb,
  projects jsonb null default '[]'::jsonb,
  achievements text[] null default '{}'::text[],
  languages text[] null default '{}'::text[],
  interests text[] null default '{}'::text[],
  source text null default 'resume'::text,
  is_active boolean null default true,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint professional_profiles_pkey primary key (id),
  constraint professional_profiles_user_id_key unique (user_id)
) TABLESPACE pg_default;
